### ISSUE TITLE
no train.py file

### ISSUE THREAD

**Issue by gozdedemirci** [ucuapps/WSMIS#4]
Greetings,

I am trying to run your baseline on a custom dataset. However, there is no train.py in your directory. Is there any way you can share it? Thank you.

**Comment by marichka-dobko** [comment]
Hi, we have split our train.py into a few separate files, the README is not updated about this.
For example, you can find training scripts for segmentation in this [directory](https://github.com/ucuapps/WSMIS/blob/master/model_training/segmentation/). It includes [train_pneumothorax.py](https://github.com/ucuapps/WSMIS/blob/master/model_training/segmentation/train_pneumothorax.py), and [train_pascal.py](https://github.com/ucuapps/WSMIS/blob/master/model_training/segmentation/train_pascal.py) .

We also have [another repository ](https://github.com/ucuapps/LIDChallenge2020-NoPeopleAllowed) that is related to this project, but uses ImageNet data for training. It has a more descriptive README.

**Comment by gozdedemirci** [comment]
Perfect! Thank you very much
